import http from 'node:http';
import fs from 'node:fs';
import { CopilotRuntime, copilotRuntimeNodeHttpEndpoint } from '@copilotkit/runtime';
import { BuiltInAgent } from '@copilotkit/runtime/v2';
const key = JSON.parse(fs.readFileSync(process.env.HOME + '/.config/file-manager/llm.json', 'utf8')).anthropicApiKey;
const runtime = new CopilotRuntime({ agents: { default: new BuiltInAgent({ model: 'anthropic/claude-haiku-4-5-20251001', apiKey: key }) } });
const handler = copilotRuntimeNodeHttpEndpoint({ endpoint: '/copilotkit', runtime, serviceAdapter: undefined });
const srv = http.createServer((req, res) => void handler(req, res));
srv.listen(45991, '127.0.0.1', () => console.log('up'));
setTimeout(() => process.exit(0), 30000);
