// fm-a2k — type surface for the pure tagStore.mjs persistence layer (runtime is
// plain ESM so the node test runner imports it without a transpile step).
//
// A SINGLE-FILE JSON CRUD store for user tag rules. Pure persistence — it never
// parses or evaluates a `selector`; that is the tagDsl engine's job
// (src/tagDsl.mjs: parse(selector) -> Ast, evaluate(ast, fileRow, opts)).

/** Live tags re-evaluate their `selector` against the current files; frozen
 *  tags pin a captured `snapshot` of paths instead. */
export type TagMode = 'live' | 'frozen';

/** A persisted tag rule. `selector` is a tagDsl query STRING (the same format
 *  src/tagDsl.mjs `parse()` consumes); it may contain `tag:name` atoms that
 *  reference OTHER tags, resolved later via the engine's injectable
 *  `opts.resolveTag` (a follow-up task wires that resolver to this store). */
export interface Tag {
  id: string;
  name: string;
  color: string;
  /** A tagDsl query string — see src/tagDsl.mjs for the grammar. */
  selector: string;
  mode: TagMode;
  /** Pinned paths for a frozen tag; absent for live tags. */
  snapshot?: string[];
  created_at: string;
  updated_at: string;
}

/** Fields accepted on create. id + timestamps are generated by the store. */
export interface TagCreate {
  name: string;
  selector: string;
  color?: string;
  mode?: TagMode;
  snapshot?: string[];
}

/** A partial patch for update(). id/created_at are preserved; updated_at is
 *  bumped. Pass `snapshot: null` to clear a frozen snapshot. */
export interface TagUpdate {
  name?: string;
  selector?: string;
  color?: string;
  mode?: TagMode;
  snapshot?: string[] | null;
}

/** Where the JSON file lives. Provide `file` (full path) or `dir` (the file
 *  name is appended); omit both for the cross-platform default location.
 *  The Electron host should pass `dir: app.getPath('userData')`. */
export interface TagStoreOptions {
  file?: string;
  dir?: string;
}

/** A handle bound to one JSON file. All ops read-then-atomically-rewrite. */
export declare class TagStore {
  readonly file: string;
  constructor(opts?: TagStoreOptions);
  list(): Promise<Tag[]>;
  getById(id: string): Promise<Tag | null>;
  getByName(name: string): Promise<Tag | null>;
  create(input: TagCreate): Promise<Tag>;
  update(id: string, patch: TagUpdate): Promise<Tag | null>;
  delete(id: string): Promise<boolean>;
}

/** Resolve the JSON file path used by a store with the given options. */
export declare function resolveTagsFile(opts?: TagStoreOptions): string;

/** Convenience constructor mirroring `new TagStore(opts)`. */
export declare function openTagStore(opts?: TagStoreOptions): TagStore;

export declare const _internal: {
  defaultConfigDir(): string;
  resolveTagsFile(opts?: TagStoreOptions): string;
  normalizeTag(t: unknown): Tag;
  readAll(file: string): Promise<Tag[]>;
  writeAll(file: string, tags: Tag[]): Promise<void>;
  APP_DIR: string;
  FILE_NAME: string;
};
